version: "2.2"
services:
  mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ktor
      MYSQL_ROOT_PASSWORD: root
    security_opt:
      - seccomp:unconfined
  ktor-app:
    build: .
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb